_target_: utils.api.create_api_call
model: gemini/gemini-3-pro-preview
delay: 0
temperature: 1.0 # Changing the temperature (setting it below 1.0) may lead to unexpected behavior, such as looping or degraded performance, particularly in complex mathematical or reasoning tasks.
max_tokens: null
reasoning_effort: null
additional_drop_params:
    - max_tokens
    - reasoning_effort
