_target_: nudging.distillation.DistillationEdit

# Strategy name for logging/results organization
name: distillation

# The distillation prompt e.g. result from auto-interpretation analysis
distillation_prompt: ???

# Use default image editor from config
image_editing_model: ${editor}
