_target_: utils.models.LiteLLM
api_call:
  _target_: utils.api.create_api_call
  model: gemini/gemini-3-pro-image-preview
  delay: 0
  temperature: null
  max_tokens: null
  reasoning_effort: null
  additional_drop_params:
    - temperature
    - max_tokens
    - reasoning_effort
